name: fun

on:
  push:
    branches:
      - master

jobs:
  build:
    name: clingo ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: fun
        channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - run: |
        conda install -y cffi
        python gen.py
        python fun.py
